#:kivy 1.0.9

<Ball>:
    size: 50, 50
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<Paddle>:
    size: 200, 25
    canvas:
        Rectangle:
            pos:self.pos
            size:self.size

<Game>:
    ball: ball
    paddle: paddle

    Ball:
        id: ball
        center: self.parent.center

    Paddle:
        id: paddle
        center_x: root.center_x
        center_y: root.x

